### ISSUE TITLE
[Enhancement] Release gate inprovement (second/final stage)

### ISSUE THREAD

**Issue by yqlbu** [daeuniverse/dae-bot#46]
## Context

Given a scenario of `release promotion` - from `v0.2.0rc4` to `v0.2.0`

In the second stage of the release process where we create a PR to include release changelogs associated with the future release, once the PR is reviewed and merged, a new release tag will be created and based on the latest commit ref in `main`. This is regarded as `release:auto` process; in other words, the release tag will be created automatically on the fly. To overwrite this default behavior, we need to add logic to disable `auto-tag-creation`.

## Implementation Plan

Monitor if `release:manual` is set in the release-branch PR; if so, disable `auto-tag-creation`. As a result, one of the members in @daeuniverse/governance team has to do the followings:

- [x] Fork a branch (e.g forked-v0.2.0rc1) based on the previous release tag
- [x] Manually create an `annotated` release tag (e.g 0.2.0) based on the forked branch (forked-v0.2.0rc1)
- [x] Cherry-pick any necessary commits from `origin/main` to the new release tag
- [x] Manually trigger the `release` workflow with an input of the new release tag

**Comment by yqlbu** [comment]
@kunish @mzz2017 Any thoughts/comments on top of this scheme?

**Comment by mzz2017** [comment]
LGTM

**Comment by yqlbu** [comment]
> LGTM

Cool, I will start working on the implementation followed by the above plan.
